package com.healthwalk.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table car.
 */
public class CarBean {

    private Long id;
    private Integer user_id;
    private String date;
    private String time_begin;
    private String time_end;
    private String route;
    private String road;
    private String exhaust;
    private String voc;
    private String co;
    private String pm;
    private String nox;
    private String gasoline;
    private Integer carkind_id;
    private Integer drive;

    public CarBean() {
    }

    public CarBean(Long id) {
        this.id = id;
    }

    public CarBean(Long id, Integer user_id, String date, String time_begin, String time_end, String route, String road, String exhaust, String voc, String co, String pm, String nox, String gasoline, Integer carkind_id, Integer drive) {
        this.id = id;
        this.user_id = user_id;
        this.date = date;
        this.time_begin = time_begin;
        this.time_end = time_end;
        this.route = route;
        this.road = road;
        this.exhaust = exhaust;
        this.voc = voc;
        this.co = co;
        this.pm = pm;
        this.nox = nox;
        this.gasoline = gasoline;
        this.carkind_id = carkind_id;
        this.drive = drive;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTime_begin() {
        return time_begin;
    }

    public void setTime_begin(String time_begin) {
        this.time_begin = time_begin;
    }

    public String getTime_end() {
        return time_end;
    }

    public void setTime_end(String time_end) {
        this.time_end = time_end;
    }

    public String getRoute() {
        return route;
    }

    public void setRoute(String route) {
        this.route = route;
    }

    public String getRoad() {
        return road;
    }

    public void setRoad(String road) {
        this.road = road;
    }

    public String getExhaust() {
        return exhaust;
    }

    public void setExhaust(String exhaust) {
        this.exhaust = exhaust;
    }

    public String getVoc() {
        return voc;
    }

    public void setVoc(String voc) {
        this.voc = voc;
    }

    public String getCo() {
        return co;
    }

    public void setCo(String co) {
        this.co = co;
    }

    public String getPm() {
        return pm;
    }

    public void setPm(String pm) {
        this.pm = pm;
    }

    public String getNox() {
        return nox;
    }

    public void setNox(String nox) {
        this.nox = nox;
    }

    public String getGasoline() {
        return gasoline;
    }

    public void setGasoline(String gasoline) {
        this.gasoline = gasoline;
    }

    public Integer getCarkind_id() {
        return carkind_id;
    }

    public void setCarkind_id(Integer carkind_id) {
        this.carkind_id = carkind_id;
    }

    public Integer getDrive() {
        return drive;
    }

    public void setDrive(Integer drive) {
        this.drive = drive;
    }

}
