package com.healthwalk.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.healthwalk.bean.PersonBean;
import com.healthwalk.bean.CarBean;

import com.healthwalk.dao.PersonBeanDao;
import com.healthwalk.dao.CarBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personBeanDaoConfig;
    private final DaoConfig carBeanDaoConfig;

    private final PersonBeanDao personBeanDao;
    private final CarBeanDao carBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personBeanDaoConfig = daoConfigMap.get(PersonBeanDao.class).clone();
        personBeanDaoConfig.initIdentityScope(type);

        carBeanDaoConfig = daoConfigMap.get(CarBeanDao.class).clone();
        carBeanDaoConfig.initIdentityScope(type);

        personBeanDao = new PersonBeanDao(personBeanDaoConfig, this);
        carBeanDao = new CarBeanDao(carBeanDaoConfig, this);

        registerDao(PersonBean.class, personBeanDao);
        registerDao(CarBean.class, carBeanDao);
    }
    
    public void clear() {
        personBeanDaoConfig.getIdentityScope().clear();
        carBeanDaoConfig.getIdentityScope().clear();
    }

    public PersonBeanDao getPersonBeanDao() {
        return personBeanDao;
    }

    public CarBeanDao getCarBeanDao() {
        return carBeanDao;
    }

}
